"""PDF / DOCX rendering + delivery for the Broom Service documents, forms,
and QuickBooks-style payroll printing module.

Rendering is data-driven from the prefab definitions in legal_forms.py
or custom form definitions stored in the database.
"""

import asyncio
import io
import re
from email.message import EmailMessage
from email.utils import formataddr

from fpdf import FPDF

try:
    import aiosmtplib
except ImportError:  # pragma: no cover
    aiosmtplib = None


# ---------------------------------------------------------------------------
# Money helpers
# ---------------------------------------------------------------------------

ONES = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
        "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen",
        "Seventeen", "Eighteen", "Nineteen"]
TENS = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"]


def _words_under_1000(n):
    out = []
    if n >= 100:
        out.append(ONES[n // 100] + " Hundred")
        n %= 100
    if 0 < n < 20:
        out.append(ONES[n])
    elif n >= 20:
        out.append(TENS[n // 10])
        if n % 10:
            out.append(ONES[n % 10])
    return " ".join(out)


def amount_to_words(cents: int) -> str:
    """Convert an amount in cents to the words used on the check amount line."""
    dollars, remainder = divmod(int(cents or 0), 100)
    if dollars == 0:
        parts = "Zero"
    elif dollars < 1_000_000:
        parts = _words_under_1000(dollars)
    else:
        millions, rest = divmod(dollars, 1_000_000)
        parts = _words_under_1000(millions) + " Million"
        if rest:
            parts += " " + _words_under_1000(rest)
    return f"{parts.title()} and {remainder:02d}/100 Dollars"


def _money(cents: int) -> str:
    try:
        return f"${int(cents or 0) / 100:,.2f}"
    except (TypeError, ValueError):
        return "$0.00"


def _pdf_text(value) -> str:
    """Sanitize a value for core-font (latin-1) PDF cells.

    Core PDF fonts can only encode latin-1; em-dashes, smart quotes, bullets,
    etc. otherwise raise FPDFUnicodeEncodingException and kill the whole PDF.
    We approximate the common ones and drop anything else.
    """
    text = str(value or "")
    return (
        text.replace("\u2014", "--")   # em dash
        .replace("\u2013", "-")        # en dash
        .replace("\u2018", "'").replace("\u2019", "'")   # curly single quotes
        .replace("\u201c", '"').replace("\u201d", '"')   # curly double quotes
        .replace("\u2026", "...")      # ellipsis
        .replace("\u00b7", ".")
        .replace("\u2022", "-")        # bullet
        .encode("latin-1", "replace").decode("latin-1")
    )


# ---------------------------------------------------------------------------
# Generic document renderer (prefab + custom forms)
# ---------------------------------------------------------------------------

def _field_value(values: dict, key: str) -> str:
    val = (values or {}).get(key)
    return "" if val is None else str(val).strip()


class _BasePdf(FPDF):
    def footer(self):
        self.set_y(-12)
        self.set_font("helvetica", size=8)
        self.set_text_color(140, 140, 150)
        self.cell(0, 8, _pdf_text(f"Page {self.page_no()} - Generated by Broom Service"), align="C")


def render_doc_pdf(form: dict, values: dict) -> bytes:
    pdf = _BasePdf(format="Letter")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pdf.set_margins(20, 15, 20)

    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(20, 20, 25)
    pdf.multi_cell(0, 7, _pdf_text(form.get("title", "Document")), align="L")

    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(110, 110, 120)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, _pdf_text(f"DATE: {_field_value(values, 'date') or '________________'}"))

    y = pdf.get_y()
    pdf.set_draw_color(79, 70, 229)
    pdf.set_line_width(0.6)
    pdf.line(20, y, pdf.w - 20, y)
    pdf.ln(4)

    for section in form.get("sections", []):
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(79, 70, 229)
        pdf.ln(2)
        pdf.multi_cell(0, 6, _pdf_text(section.get("heading", "")))
        pdf.ln(1)
        for fld in section.get("fields", []):
            label = fld.get("label", fld.get("key", ""))
            val = _field_value(values, fld.get("key"))
            line = f"{label}:  {val}" if val else f"{label}:"
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(20, 20, 25)
            pdf.multi_cell(0, 5, _pdf_text(line))
            if not val:
                pdf.set_draw_color(200, 200, 210)
                pdf.set_line_width(0.3)
                pdf.line(20, pdf.get_y() + 1, min(pdf.w - 40, 20 + 150), pdf.get_y() + 1)
                pdf.ln(3)
            else:
                pdf.ln(2)

    for clause in form.get("agreements", []):
        pdf.ln(2)
        pdf.set_draw_color(200, 200, 210)
        pdf.set_line_width(0.3)
        pdf.line(20, pdf.get_y(), pdf.w - 20, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(30, 30, 40)
        pdf.multi_cell(0, 5.2, _pdf_text("•  " + clause))

    if form.get("signatories"):
        pdf.ln(6)
        halfway = (pdf.w - 40) / 2
        for sig in form["signatories"]:
            pdf.ln(6)
            pdf.set_draw_color(60, 60, 70)
            pdf.set_line_width(0.4)
            pdf.line(20, pdf.get_y(), 20 + (halfway - 10), pdf.get_y())
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(90, 90, 100)
            pdf.set_xy(20, pdf.get_y() + 2)
            pdf.cell(0, 5, _pdf_text(sig + " Signature & Date"))
            pdf.ln(10)

    if form.get("disclaimer"):
        pdf.ln(2)
        pdf.set_font("helvetica", "I", 8)
        pdf.set_text_color(150, 150, 155)
        pdf.multi_cell(0, 4.5, _pdf_text("Note: " + form["disclaimer"]))

    return bytes(pdf.output())


def render_doc_docx(form: dict, values: dict) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor

    doc = Document()
    styles = doc.styles["Normal"]
    styles.font.name = "Calibri"
    styles.font.size = Pt(10.5)

    h = doc.add_heading(form.get("title", "Document"), level=0)
    h.runs[0].font.color.rgb = RGBColor(0x10, 0x14, 0x19)

    date_line = doc.add_paragraph()
    r = date_line.add_run(f"DATE: {_field_value(values, 'date') or '________________'}")
    r.font.size = Pt(9)
    r.font.color.rgb = RGBColor(0x6E, 0x6E, 0x78)

    def field_line(field):
        label = field.get("label", field.get("key", ""))
        val = _field_value(values, field.get("key"))
        if val:
            p = doc.add_paragraph(f"{label}:  {val}")
        else:
            p = doc.add_paragraph(f"{label}:  " + "_" * 42)
        p.paragraph_format.space_after = Pt(4)
        return p

    for section in form.get("sections", []):
        doc.add_heading(section.get("heading", ""), level=1)
        for fld in section.get("fields", []):
            field_line(fld)

    for clause in form.get("agreements", []):
        p = doc.add_paragraph(style="List Bullet")
        p.add_run(clause)

    if form.get("signatories"):
        doc.add_paragraph()
        for sig in form["signatories"]:
            doc.add_paragraph()
            sp = doc.add_paragraph(f"____________________________________   {sig} Signature & Date")
            sp.paragraph_format.space_after = Pt(10)

    if form.get("disclaimer"):
        dp = doc.add_paragraph()
        dr = dp.add_run("Note: " + form["disclaimer"])
        dr.font.size = Pt(8)
        dr.font.italic = True
        dr.font.color.rgb = RGBColor(0x96, 0x96, 0x9B)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def render_document(form: dict, values: dict, fmt: str) -> bytes:
    if fmt == "docx":
        return render_doc_docx(form, values)
    return render_doc_pdf(form, values)


# ---------------------------------------------------------------------------
# Pay stub + printable check rendering
# ---------------------------------------------------------------------------

def render_pay_stub_pdf(stub) -> bytes:
    pdf = _BasePdf(format="Letter")
    pdf.add_page()
    pdf.set_margins(20, 15, 20)

    pdf.set_font("helvetica", "B", 17)
    pdf.set_text_color(15, 20, 30)
    pdf.cell(0, 8, "Broom Service", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(110, 110, 120)
    pdf.cell(0, 5, "PAY STUB", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    y = pdf.get_y()
    pdf.set_draw_color(79, 70, 229)
    pdf.set_line_width(0.7)
    pdf.line(20, y, pdf.w - 20, y)
    pdf.ln(4)

    info = [
        ("Employee", stub.get("worker_name", "")),
        ("Pay period", f"{stub.get('period_start')}  to  {stub.get('period_end')}"),
        ("Jobs completed", str(stub.get("job_count", 0))),
        ("Check number", str(stub.get("check_number") or "--")),
        ("Pay date", str(stub.get("pay_date") or "________________")),
    ]
    pdf.set_font("helvetica", "", 10)
    for label, val in info:
        pdf.set_text_color(90, 90, 100)
        pdf.cell(50, 6, label.upper(), new_x="END")
        pdf.set_text_color(20, 20, 25)
        pdf.cell(0, 6, _pdf_text(val), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    rows = [
        ("GROSS PAY", stub.get("gross_cents", 0), False),
        ("Federal withholding", stub.get("fed_cents", 0), True),
        ("State withholding", stub.get("state_cents", 0), True),
        ("FICA / Medicare", stub.get("fica_cents", 0), True),
        ("Other deductions", stub.get("other_cents", 0), True),
    ]
    pdf.set_font("helvetica", "", 10.5)
    for label, cents, deduct in rows:
        pdf.set_draw_color(230, 230, 235)
        pdf.set_line_width(0.3)
        pdf.line(20, pdf.get_y() + 6, pdf.w - 20, pdf.get_y() + 6)
        if deduct:
            pdf.set_text_color(180, 40, 40)
        else:
            pdf.set_text_color(20, 20, 25)
        pdf.cell(0, 7, label, new_x="END")
        pdf.cell(0, 7, _money(cents), align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(2)
    pdf.set_fill_color(16, 185, 129)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(255, 255, 255)
    pdf.set_draw_color(16, 185, 129)
    pdf.rect(20, pdf.get_y(), pdf.w - 40, 9, style="F")
    pdf.set_xy(20, pdf.get_y() + 1)
    pdf.cell(pdf.w - 40, 7, "NET PAY", align="C")

    net = (stub.get("gross_cents") or 0) - (stub.get("fed_cents") or 0) - (stub.get("state_cents") or 0) - (stub.get("fica_cents") or 0) - (stub.get("other_cents") or 0)
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(20, 20, 25)
    pdf.set_fill_color(16, 185, 129)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(20, pdf.get_y() + 2)
    pdf.cell(pdf.w - 40, 7, _money(net), align="C")
    pdf.set_text_color(20, 20, 25)

    pdf.ln(14)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(150, 150, 155)
    pdf.multi_cell(0, 4.5, _pdf_text("Note: This is a generated record from the Broom Service accounting module. Verify withholdings with your accountant."))

    # QR-ish reference
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(90, 90, 100)
    pdf.set_xy(20, pdf.h - 24)
    pdf.cell(0, 5, _pdf_text(f"Stub ID: {stub.get('id', '')}  ·  Generated {stub.get('generated_at', '')}"))

    return bytes(pdf.output())


def render_check_pdf(check: dict) -> bytes:
    """Printable check + attached stub on one letter page.

    pays like: check['payee'], check['amount_cents'], check['check_number'],
    check['date'], check['memo'], check['stub'] (dict for stub rows), and
    check['bank']['name'/'holder'/'routing'/'account'/'address']."""

    pdf = _BasePdf(format="Letter")
    pdf.add_page()
    pdf.set_margins(20, 15, 20)

    bank = check.get("bank", {}) or {}

    # --- Stub (top third) ---
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(20, 20, 25)
    pdf.cell(0, 6, _pdf_text(f"CHECK STUB  ·  {check.get('check_number', '')}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(90, 90, 100)
    pdf.cell(0, 5, _pdf_text(bank.get('holder', 'Broom Service')), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, _pdf_text("Pay to:  " + str(check.get("payee", ""))), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, _pdf_text("Date:  " + str(check.get("date", ""))), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    stub_rows = check.get("stub") or [("Amount", check.get("amount_cents", 0))]
    pdf.set_font("helvetica", "", 9)
    for label, cents in stub_rows:
        pdf.cell(0, 5.5, _pdf_text(label), new_x="END")
        pdf.cell(0, 5.5, _money(cents), align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 6, "TOTAL", new_x="END")
    pdf.cell(0, 6, _money(check.get("amount_cents", 0)), align="R", new_x="LMARGIN", new_y="NEXT")

    # perforation line
    pdf.set_draw_color(180, 180, 190)
    pdf.set_line_width(0.4)
    y = pdf.get_y() + 6
    pdf.set_dash_pattern(dash=2, gap=2)
    pdf.line(20, y, pdf.w - 20, y)
    pdf.set_dash_pattern()
    pdf.ln(10)

    # --- Check body ---
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(20, 20, 25)
    pdf.cell(0, 8, _pdf_text(bank.get("holder", "Broom Service")), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(90, 90, 100)
    pdf.multi_cell(0, 4, _pdf_text(str(bank.get("address", "")) + (" " + str(bank.get("city_state_zip", ""))).strip()))

    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(20, 20, 25)
    date_str = str(check.get("date", ""))
    pdf.cell(70, 7, "")  # left spacer
    pdf.cell(0, 7, _pdf_text("DATE  " + date_str), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # pay to / amount box row
    pdf.cell(8, 8, "")
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(90, 90, 100)
    pdf.cell(30, 5, "PAY TO THE ORDER OF")
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(20, 20, 25)
    pdf.cell(0, 8, _pdf_text("  " + str(check.get("payee", "")) + "  "), border=1, new_x="END")
    # amount box
    pdf.cell(0, 8, "")
    pdf.set_draw_color(90, 90, 100)
    pdf.set_line_width(0.4)
    pdf.set_xy(pdf.l_margin, pdf.get_y())
    box_x = pdf.w - pdf.r_margin - 45
    pdf.set_font("helvetica", "B", 11)
    y0 = pdf.get_y()
    pdf.rect(box_x, y0, 45, 8)
    pdf.set_xy(box_x, y0 + 1.5)
    pdf.cell(45, 5, _money(check.get("amount_cents", 0)), align="C")
    pdf.set_xy(pdf.l_margin, y0)
    pdf.ln(9)

    # amount in words
    pdf.cell(8, 7, "")
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(90, 90, 100)
    pdf.cell(30, 5, "AMOUNT")
    pdf.set_font("helvetica", "", 9.5)
    pdf.set_text_color(20, 20, 25)
    pdf.cell(pdf.w - pdf.l_margin - pdf.r_margin - 40, 7, _pdf_text("  " + amount_to_words(check.get("amount_cents", 0)) + "  "), border=1, new_x="LMARGIN", new_y="NEXT")

    memo = check.get("memo") or ""
    pdf.ln(2)
    pdf.cell(8, 7, "")
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(90, 90, 100)
    pdf.cell(20, 5, "MEMO")
    pdf.set_font("helvetica", "", 9.5)
    pdf.set_text_color(20, 20, 25)
    pdf.cell(0, 7, _pdf_text("  " + memo), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # signature
    pdf.cell(8, 6, "")
    pdf.set_draw_color(60, 60, 70)
    pdf.set_line_width(0.5)
    pdf.line(pdf.l_margin + 30, pdf.get_y(), pdf.l_margin + 120, pdf.get_y())
    pdf.ln(6)
    pdf.cell(8, 5, "")
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(90, 90, 100)
    pdf.cell(120, 5, "Authorized Signature")
    pdf.ln(8)

    # MICR style line (visual — print on pre-encoded stock for real checks)
    pdf.set_font("Courier", "B", 9)
    pdf.set_text_color(10, 10, 15)
    micr = f"|:000000000:{bank.get('routing', '').zfill(9)}:{bank.get('account', '').zfill(12)}:{str(check.get('check_number', '')).zfill(4)}||"
    pdf.set_xy(pdf.l_margin, pdf.h - 24)
    pdf.cell(0, 5, micr)

    return bytes(pdf.output())


# ---------------------------------------------------------------------------
# Delivery: SMTP email + SignalWire SMS link
# ---------------------------------------------------------------------------

SMTP_KEYS = ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASS", "SMTP_FROM", "SMTP_NAME", "SMTP_TLS"]


def smtp_config_from_env() -> dict:
    return {
        "SMTP_HOST": os_getenv("SMTP_HOST", ""),
        "SMTP_PORT": os_getenv("SMTP_PORT", "587"),
        "SMTP_USER": os_getenv("SMTP_USER", ""),
        "SMTP_PASS": os_getenv("SMTP_PASS", ""),
        "SMTP_FROM": os_getenv("SMTP_FROM", ""),
        "SMTP_NAME": os_getenv("SMTP_NAME", "Broom Service"),
        "SMTP_TLS": os_getenv("SMTP_TLS", "starttls"),  # starttls | ssl | none
    }


def os_getenv(key, default=""):
    import os
    return os.getenv(key, default)


def smtp_configured(cfg: dict) -> bool:
    return bool(cfg.get("SMTP_HOST") and cfg.get("SMTP_FROM"))

def mime_type(filename: str):
    if filename.endswith(".docx"):
        return "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    return "application/pdf"


async def _send_via_resend_api(cfg: dict, to: str, subject: str, body: str, physical: str, api_key: str) -> bool:
    import asyncio
    import json as _json
    import urllib.request
    import re as _re

    html_body = body.replace("\n", "<br>")
    text_body = _re.sub(r"<br\s*/?>", "\n", html_body)
    if physical:
        html_body += "\n\n" + physical.replace("\n", "<br>")
        text_body += "\n\n" + physical

    frm = cfg.get("SMTP_FROM") or ""
    name = (cfg.get("SMTP_NAME") or "").strip()
    sender = f"{name} <{frm}>" if name else frm
    payload = _json.dumps(
        {"from": sender, "to": [to], "subject": subject, "text": text_body, "html": html_body}
    ).encode()

    def _post() -> bool:
        import urllib.error

        ureq = urllib.request.Request(
            "https://api.resend.com/emails",
            data=payload,
            method="POST",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "Accept": "application/json",
                # Cloudflare in front of api.resend.com rejects non-browser
                # user agents with error 1010, so present a normal one.
                "User-Agent": (
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
                ),
            },
        )
        try:
            with urllib.request.urlopen(ureq, timeout=30) as resp:
                if resp.status < 200 or resp.status >= 300:
                    detail = (resp.read() or b"").decode(errors="replace")[:300]
                    raise RuntimeError(f"Resend HTTP {resp.status}: {detail}")
                return True
        except urllib.error.HTTPError as he:
            detail = (he.read() or b"").decode(errors="replace")[:400]
            raise RuntimeError(f"Resend HTTP {he.code}: {detail}") from he

    return await asyncio.to_thread(_post)


def ses_configured() -> bool:
    return bool(
        os_getenv("AWS_ACCESS_KEY_ID", "").strip()
        and os_getenv("AWS_SECRET_ACCESS_KEY", "").strip()
    )


def _send_via_ses(cfg: dict, to: str, raw: bytes) -> bool:
    import boto3
    from botocore.config import Config as BotoConfig

    region = os_getenv("SES_REGION", "us-east-1").strip() or "us-east-1"
    client = boto3.client(
        "ses",
        region_name=region,
        config=BotoConfig(
            connect_timeout=10,
            read_timeout=20,
            retries={"max_attempts": 2, "mode": "standard"},
        ),
    )
    resp = client.send_raw_email(
        Source=formataddr((cfg.get("SMTP_NAME", ""), cfg.get("SMTP_FROM", ""))),
        Destinations=[to],
        RawMessage={"Data": raw},
    )
    return bool(resp.get("MessageId"))


async def send_email(cfg: dict, to: str, subject: str, body: str, attachment: bytes = None, filename: str = ""):
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = formataddr((cfg.get("SMTP_NAME", ""), cfg.get("SMTP_FROM", "")))
    msg["To"] = to
    physical = (os_getenv("SENDER_PHYSICAL_ADDRESS", "")).strip()
    msg.set_content(body + ("\n\n" + physical if physical else ""))
    if attachment and filename:
        msg.add_attachment(
            attachment, maintype="application", subtype=mime_type(filename).split("/")[1], filename=filename
        )

    host = cfg.get("SMTP_HOST", "")
    port = int(cfg.get("SMTP_PORT") or 587)
    tls = (cfg.get("SMTP_TLS") or "starttls").lower()
    connect_timeout = int(os_getenv("SMTP_CONNECT_TIMEOUT", "15") or 15)
    key = os_getenv("RESEND_API_KEY", "").strip()
    if not key and (host or "").strip() == "smtp.resend.com":
        key = (cfg.get("SMTP_PASS") or "").strip()
    resend_key = key

    # Cloud hosts (Railway) frequently block outbound SMTP egress entirely.
    # Prefer the Resend HTTPS REST API when a key is available, then fall back
    # to the SMTP ladder below.
    if resend_key and (cfg.get("SMTP_FROM") or ""):
        try:
            sent_ok = await _send_via_resend_api(cfg, to, subject, body, physical, resend_key)
            if sent_ok:
                return True
        except Exception as e:
            print(f"[EMAIL] Resend API attempt failed: {e}")

    # AWS SES over HTTPS (443): works from cloud hosts whose SMTP egress is
    # firewalled. When creds are present SES is authoritative, so a failure is
    # surfaced immediately rather than burning time on unreachable SMTP ports.
    if ses_configured() and (cfg.get("SMTP_FROM") or ""):
        return await asyncio.to_thread(_send_via_ses, cfg, to, msg.as_bytes())

    # Build a retry ladder of (port, mode) candidates. Namecheap and other
    # providers intermittently drop cloud-host egress, so we race STARTTLS
    # and implicit SSL candidates concurrently and use whichever connects.
    ladder = []
    if port not in (25, 465, 587):
        ladder.append((port, tls if tls in ("ssl", "starttls") else "starttls"))
    for candidate in (
        (587, "starttls"),
        (465, "ssl"),
        (25, "starttls"),
    ):
        if candidate not in ladder:
            ladder.append(candidate)
    tail = [x for x in ladder if x[0] == port]
    if tail:
        ladder.remove(tail[0])
        ladder.insert(0, (port, tls if tls in ("ssl", "starttls") else "starttls"))

    async def _try(port: int, mode: str, ip: str | None = None):
        kwargs = dict(hostname=ip or host, port=port, validate_certs=False, timeout=connect_timeout)
        if ip:
            kwargs["server_hostname"] = host
        if cfg.get("SMTP_USER"):
            kwargs.update(username=cfg["SMTP_USER"], password=cfg.get("SMTP_PASS", ""))
        if mode == "ssl":
            await aiosmtplib.send(msg, use_tls=True, **kwargs)
        elif mode == "starttls":
            await aiosmtplib.send(msg, start_tls=True, **kwargs)
        else:
            await aiosmtplib.send(msg, start_tls=False, **kwargs)

    # Some cloud hosts only route IPv4 correctly; resolve IPv4 up front and,
    # if the hostname attempts fail, retry each candidate against a literal
    # IPv4 address (SNI kept via server_hostname).
    ipv4_addresses: list[str] = []
    try:
        import socket

        infos = await asyncio.getaddrinfo(host, port, family=socket.AF_INET, type=socket.SOCK_STREAM)
        ipv4_addresses = list(dict.fromkeys(i[4][0] for i in infos))
    except Exception:
        pass

    # Try the candidates in priority order and stop at the first success.
    # Racing with FIRST_EXCEPTION was unreliable: a fast refusal (e.g. closed
    # port 25) cancelled the in-flight attempt that would have succeeded on
    # STARTTLS, so email appeared broken even with a valid SMTP config.
    last_error: Exception | None = None
    for port, mode in ladder:
        try:
            await _try(port, mode)
            return True
        except Exception as e:
            last_error = e
            print(f"[EMAIL] SMTP {host}:{port}/{mode} attempt failed: {e}")
    for ip in ipv4_addresses:
        for port, mode in ((587, "starttls"), (465, "ssl")):
            try:
                await _try(port, mode, ip=ip)
                return True
            except Exception as e:
                last_error = e
                print(f"[EMAIL] SMTP {host} ({ip}):{port}/{mode} attempt failed: {e}")
    raise last_error or RuntimeError(f"SMTP {host} is unreachable (no candidates left to try).")